"""empty db

Revision ID: 7e48cd43220a
Revises:
Create Date: 2023-01-09 11:33:57.041394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e48cd43220a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'country',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=255), nullable=False),
        sa.Column('caption_languages', sa.String(length=25), nullable=False),
        sa.Column('depicts_language', sa.String(length=13), nullable=False),
        sa.Column('contrib', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table(
        'campaign',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('campaign_name', sa.String(length=200), nullable=False),
        sa.Column('campaign_images', sa.Integer(), nullable=True),
        sa.Column('update_status', sa.Integer(), nullable=True),
        sa.Column('campaign_contributions', sa.Integer(), nullable=True),
        sa.Column('campaign_participants', sa.Integer(), nullable=True),
        sa.Column('campaign_image', sa.String(length=200), nullable=True),
        sa.Column('start_date', sa.Date(), nullable=False),
        sa.Column('campaign_manager', sa.String(length=15), nullable=True),
        sa.Column('manager_id', sa.Integer(), nullable=False),
        sa.Column('end_date', sa.Date(), nullable=True),
        sa.Column('status', sa.Boolean(), nullable=False),
        sa.Column('short_description', sa.Text(), nullable=False),
        sa.Column('long_description', sa.Text(), nullable=False),
        sa.Column('categories', sa.Text(), nullable=False),
        sa.Column('creation_date', sa.Date(), nullable=True),
        sa.Column('campaign_type', sa.Boolean(), nullable=True),
        sa.Column('depicts_metadata', sa.Boolean(), nullable=True),
        sa.Column('captions_metadata', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['manager_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'contribution',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=20), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('campaign_id', sa.Integer(), nullable=False),
        sa.Column('file', sa.String(length=210), nullable=False),
        sa.Column('edit_type', sa.String(length=10), nullable=False),
        sa.Column('edit_action', sa.String(length=7), nullable=False),
        sa.Column('country', sa.String(length=50), nullable=False),
        sa.Column('depict_item', sa.String(length=15), nullable=True),
        sa.Column('depict_prominent', sa.Boolean(), nullable=True),
        sa.Column('caption_language', sa.String(length=5), nullable=True),
        sa.Column('caption_text', sa.String(length=200), nullable=True),
        sa.Column('date', sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'image',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('page_id', sa.Integer(), nullable=False),
        sa.Column('campaign_id', sa.Integer(), nullable=False),
        sa.Column('country_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
        sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'suggestion',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('campaign_id', sa.Integer(), nullable=False),
        sa.Column('file', sa.String(length=240), nullable=False),
        sa.Column('depict_item', sa.String(length=15), nullable=True),
        sa.Column('update_status', sa.Integer(), nullable=True),
        sa.Column('google_vision', sa.Boolean(), nullable=True),
        sa.Column('metadata_to_concept', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suggestion_id'), 'suggestion', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_suggestion_id'), table_name='suggestion')
    op.drop_table('suggestion')
    op.drop_table('image')
    op.drop_table('contribution')
    op.drop_table('campaign')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_table('country')
    # ### end Alembic commands ###
