"""initial migration

Revision ID: c8b4669f574b
Revises:
Create Date: 2022-12-19 23:28:30.209969

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c8b4669f574b'
down_revision = '7e48cd43220a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'deny_list_category',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('category_name', sa.String(length=250), nullable=False),
        sa.Column('reason', sa.String(length=240), nullable=False),
        sa.PrimaryKeyConstraint('id'))

    op.create_index(op.f('ix_deny_list_category_id'), 'deny_list_category', ['id'], unique=False)
    op.create_table(
        'deny_list',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('wikidata_item', sa.String(length=15), nullable=False),
        sa.Column('category', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['category'], ['deny_list_category.id'], ),
        sa.PrimaryKeyConstraint('id'))

    op.create_index(op.f('ix_deny_list_id'), 'deny_list', ['id'], unique=False)

    # Add denylist category Data
    # get metadata from current connection
    meta = sa.MetaData(bind=op.get_bind())

    # pass in tuple with tables we want to reflect, otherwise whole database will get reflected
    meta.reflect(only=('deny_list_category',))

    # define table representation
    deny_list_category = sa.Table('deny_list_category', meta)

    # insert records
    op.bulk_insert(
        deny_list_category,
        [
            {'id': 1, 'category_name': 'Colors', 'reason': 'Colors should never be added directly as a Depict statement. Add as a qualifier instead using the "color" property'},
            {'id': 2, 'category_name': 'Adjectives', 'reason': ''},
            {'id': 3, 'category_name': 'Odd Nouns', 'reason': ''},
            {'id': 4, 'category_name': 'Time oriented terms', 'reason': ''}
        ]
    )

    meta.reflect(only=('deny_list',))

    # define table representation
    deny_list = sa.Table('deny_list', meta)
    
    # insert records into denylist table
    op.bulk_insert(
        deny_list,
        [
            {'id': 1, 'wikidata_item': 'Q23445', 'category': 1}, {'id': 2, 'wikidata_item': 'Q3142', 'category': 1}, {'id': 3, 'wikidata_item': 'Q3133', 'category': 1},
            {'id': 4, 'wikidata_item': 'Q39338', 'category': 1}, {'id': 5, 'wikidata_item': 'Q428124', 'category': 1}, {'id': 6, 'wikidata_item': 'Q3257809', 'category': 1}, {'id': 7, 'wikidata_item': 'Q23444', 'category': 1},
            {'id': 8, 'wikidata_item': 'Q42519', 'category': 1}, {'id': 9, 'wikidata_item': 'Q47071', 'category': 1}, {'id': 10, 'wikidata_item': 'Q843607', 'category': 1}, {'id': 11, 'wikidata_item': 'Q10296772', 'category': 1},
            {'id': 12, 'wikidata_item': 'Q373058', 'category': 1}, {'id': 13, 'wikidata_item': 'Q317802', 'category': 1}, {'id': 14, 'wikidata_item': 'Q1670336', 'category': 1}, {'id': 15, 'wikidata_item': 'Q2778382', 'category': 1},
            {'id': 16, 'wikidata_item': 'Q1078214', 'category': 1}, {'id': 17, 'wikidata_item': 'Q906936', 'category': 1}, {'id': 18, 'wikidata_item': 'Q543923', 'category': 1}, {'id': 19, 'wikidata_item': 'Q2015138', 'category': 1},
            {'id': 20, 'wikidata_item': 'Q767608', 'category': 1}, {'id': 21, 'wikidata_item': 'Q3518540', 'category': 1}, {'id': 22, 'wikidata_item': 'Q5960345', 'category': 1}, {'id': 23, 'wikidata_item': 'Q3014419', 'category': 1},
            {'id': 24, 'wikidata_item': 'Q454847', 'category': 1}, {'id': 25, 'wikidata_item': 'Q679355', 'category': 1}, {'id': 26, 'wikidata_item': 'Q1324818', 'category': 1}, {'id': 27, 'wikidata_item': 'Q372973', 'category': 1},
            {'id': 28, 'wikidata_item': 'Q797446', 'category': 1}, {'id': 29, 'wikidata_item': 'Q5043987', 'category': 1}, {'id': 30, 'wikidata_item': 'Q2541418', 'category': 1}, {'id': 31, 'wikidata_item': 'Q313120', 'category': 1},
            {'id': 32, 'wikidata_item': 'Q2936397', 'category': 1}, {'id': 33, 'wikidata_item': 'Q2411228', 'category': 1}, {'id': 34, 'wikidata_item': 'Q2730433', 'category': 1}, {'id': 35, 'wikidata_item': 'Q303826', 'category': 1},
            {'id': 36, 'wikidata_item': 'Q5005364', 'category': 1}, {'id': 37, 'wikidata_item': 'Q5967009', 'category': 1}, {'id': 38, 'wikidata_item': 'Q650770', 'category': 1}, {'id': 39, 'wikidata_item': 'Q2720565', 'category': 1},
            {'id': 40, 'wikidata_item': 'Q2294993', 'category': 1}, {'id': 41, 'wikidata_item': 'Q3276756', 'category': 1}, {'id': 42, 'wikidata_item': 'Q25203611', 'category': 1}, {'id': 43, 'wikidata_item': 'Q25393814', 'category': 1},
            {'id': 44, 'wikidata_item': 'Q3309916', 'category': 1}, {'id': 45, 'wikidata_item': 'Q864152', 'category': 1}, {'id': 46, 'wikidata_item': 'Q533047', 'category': 1}, {'id': 47, 'wikidata_item': 'Q208045', 'category': 1},
            {'id': 48, 'wikidata_item': 'Q208045', 'category': 1}, {'id': 49, 'wikidata_item': 'Q2268159', 'category': 1}, {'id': 50, 'wikidata_item': 'Q48997611', 'category': 2}, {'id': 51, 'wikidata_item': 'Q10770146', 'category': 2},
            {'id': 52, 'wikidata_item': 'Q6453656', 'category': 2}, {'id': 53, 'wikidata_item': 'Q838368', 'category': 2}, {'id': 54, 'wikidata_item': 'Q296001', 'category': 2},
            {'id': 55, 'wikidata_item': 'Q1301433', 'category': 3}, {'id': 56, 'wikidata_item': 'Q1802779', 'category': 3}, {'id': 57, 'wikidata_item': 'Q6478447', 'category': 3}, {'id': 58, 'wikidata_item': 'Q2083958', 'category': 3},
            {'id': 59, 'wikidata_item': 'Q738168', 'category': 3}, {'id': 60, 'wikidata_item': 'Q696160', 'category': 3}, {'id': 61, 'wikidata_item': 'Q7239', 'category': 3}, {'id': 62, 'wikidata_item': 'Q638', 'category': 3},
            {'id': 63, 'wikidata_item': 'Q11634', 'category': 3}, {'id': 64, 'wikidata_item': 'Q11629', 'category': 3}, {'id': 65, 'wikidata_item': 'Q16502', 'category': 3}, {'id': 66, 'wikidata_item': 'Q1792644', 'category': 3},
            {'id': 67, 'wikidata_item': 'Q1190554', 'category': 3}, {'id': 68, 'wikidata_item': 'Q295469', 'category': 3}, {'id': 69, 'wikidata_item': 'Q1049799', 'category': 3}, {'id': 70, 'wikidata_item': 'Q334166', 'category': 3},
            {'id': 71, 'wikidata_item': 'Q42889', 'category': 3}, {'id': 72, 'wikidata_item': 'Q82821', 'category': 3}, {'id': 73, 'wikidata_item': 'Q3248864', 'category': 3}, {'id': 74, 'wikidata_item': 'Q53875', 'category': 3},
            {'id': 75, 'wikidata_item': 'Q37073', 'category': 3}, {'id': 76, 'wikidata_item': 'Q101998', 'category': 3}, {'id': 77, 'wikidata_item': 'Q2262382', 'category': 3}, {'id': 78, 'wikidata_item': 'Q721221', 'category': 3},
            {'id': 79, 'wikidata_item': 'Q1634416', 'category': 3}, {'id': 80, 'wikidata_item': 'Q1395149', 'category': 3}, {'id': 81, 'wikidata_item': 'Q12554', 'category': 3}, {'id': 82, 'wikidata_item': 'Q83180', 'category': 3},
            {'id': 83, 'wikidata_item': 'Q167510', 'category': 3}, {'id': 84, 'wikidata_item': 'Q43619', 'category': 3}, {'id': 85, 'wikidata_item': 'Q309', 'category': 3}, {'id': 86, 'wikidata_item': 'Q11016', 'category': 3},
            {'id': 87, 'wikidata_item': 'Q1172903', 'category': 3}, {'id': 88, 'wikidata_item': 'Q165848', 'category': 3}, {'id': 89, 'wikidata_item': 'Q211778', 'category': 3}, {'id': 90, 'wikidata_item': 'Q43238', 'category': 3},
            {'id': 91, 'wikidata_item': 'Q5135744', 'category': 3}, {'id': 92, 'wikidata_item': 'Q486972', 'category': 3}, {'id': 93, 'wikidata_item': 'Q826939', 'category': 3}, {'id': 94, 'wikidata_item': 'Q1286', 'category': 3},
            {'id': 95, 'wikidata_item': 'Q1187312', 'category': 4}, {'id': 96, 'wikidata_item': 'Q988377', 'category': 4}, {'id': 97, 'wikidata_item': 'Q1036448', 'category': 4}, {'id': 98, 'wikidata_item': 'Q1209716', 'category': 4},
            {'id': 99, 'wikidata_item': 'Q3151690', 'category': 4}, {'id': 100, 'wikidata_item': 'Q180778', 'category': 1}, {'id': 101, 'wikidata_item': 'Q943', 'category': 1}

        ]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suggestion', sa.Column('file', mysql.VARCHAR(length=240), nullable=False))
    op.drop_constraint(None, 'suggestion', type_='foreignkey')
    op.drop_column('suggestion', 'user_id')
    op.drop_column('suggestion', 'metadata_to_concept_submitted')
    op.drop_column('suggestion', 'google_vision_submitted')
    op.drop_column('suggestion', 'google_vision_confidence')
    op.drop_column('suggestion', 'date')
    op.drop_column('suggestion', 'metadata_to_concept_confidence')
    op.drop_index(op.f('ix_deny_list_id'), table_name='deny_list')
    op.drop_table('deny_list')
    op.drop_index(op.f('ix_deny_list_category_id'), table_name='deny_list_category')
    op.drop_table('deny_list_category')
    op.alter_column('suggestion', 'date', existing_type=sa.DATE(), nullable=True)
    # ### end Alembic commands ###
